### PR TITLE
urls.py update for new Django format

### PR DESCRIPTION
**Pull request by tebica**
Update urls.py to support new `urlpatterns` format.
Copy code from Mezzanine to make sure it's align to it.

### CODE REVIEW

**Comment by tebica** [comment]
@stephenmcd I saw you updated this project to support Django 1.9 and Mezzanine also use new url.py format. Can you review this PR?

FYI, [Mezzanine url format](https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/project_template/project_name/urls.py)

**Comment by stephenmcd** [comment]
Looks good, just need to remove the `patterns` import.

**Comment by tebica** [comment]
@stephenmcd I just updated my PR with removing the `patterns` import

**Comment by stephenmcd** [comment]
Awesome, thanks a lot.

**Pull request merged**
