### PR TITLE
Added support for context_object_name in drum.links views

### PR DESCRIPTION
**Pull request by rafen**
Added context_object_name support in ScoreOrderingView and UserFilterView classes.
These changes allow users that are extending these classes to specify a context_object_name. For example:

```python
    class MyLinkListView(LinkList):

        context_object_name = 'my_links'

        def get_queryset(self):
            # custom query ...
```

then in the templates it's possible to use:

```html
    {% for link in my_links %}
        <div>...
```
instead of only object_list

### CODE REVIEW

**Comment by stephenmcd** [comment]
Thanks a lot.

BTW please don't change the version number! - I'll do that when we actually push a release. Didn't matter the first time other than being a bit early, but the change in this PR is actually wrong since there isn't even a 0.2.3 yet. I'll revert it back to 0.2.2 in a moment, so no sweat.

**Comment by rafen** [comment]
Thanks for the feedback! Sorry about that, I'm changing the version to 0.2.2.

**Comment by stephenmcd** [comment]
No worries - please don't change it back, I've already done it.

**Comment by rafen** [comment]
Thanks for the fix!

**Comment by stephenmcd** [comment]
No problem :-)

**Pull request merged**
